services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8080:80"
    depends_on:
      - mysql

  flyway:
    image: flyway/flyway
    depends_on:
      - mysql
    volumes:
      - ./sql:/flyway/sql
      - ./conf:/flyway/conf
    command: -url=jdbc:mysql://mysql:3306/app_db -user=app_user -password=app_pass migrate
  
  apache:
    image: httpd:2.4
    container_name: apache-server
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./apache:/usr/local/apache2/htdocs/
#      - ./conf/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - mysql
  
volumes:
  mysql_data:

